---
# tasks file for aws_ec2

  - name: "Provision EC2 instance"
    ec2_instance:
      instance_type: "{{ instance_type | default('t2.micro') }}"
      region: "{{ region }}"
      image_id: "{{ image_id }}"
      key_name: "{{ key_name }}"
      count: "1"
      wait: true
      state: running
      tags:
        Name: "{{ item }}"
        Owner: Felix
        type: "{{ type }}"
        project: "Ansible_Demo"
        provider: "AWS"
      vpc_subnet_id: "{{subnet_ids.subnet.id}}"
      security_group: "{{my_security_group.group_id}}"
      network_interfaces:
        - assign_public_ip: yes
    loop: "{{ server_name }}"
    register: ec2_instance