---
- name: Install different update
  hosts: all
  gather_facts: no

  vars:
    categories:
      - Security
      - CriticalUpdates
      - UpdateRollups
      - DefinitionUpdates

  pre_tasks:
    - name: Disable monitoring for selected hosts
      ansible.builtin.debug:
        msg: "We need to stop monitoring for these host in Dynatrace: {{ inventory_hostname }} is {{ ansible_default_ipv4.address }}"

  tasks:
    # see 
    # https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_updates_module.html 
    # for documentation.
    - name: Install all packages listed
      ansible.windows.win_updates:
        category_names: "{{ categories | default( '*') }}"
        reboot: "{{ reboot_server | default( 'true' ) }}"
        log_path: C:\ansible_install_win_update.txt
      become: true
      become_method: runas
      become_user: SYSTEM
      register: patching_result

    - name: Display Patching Results
      ansible.builtin.debug:
        msg: "{{ patching_result | json_query('updates.*.title') }}"

  post_tasks:
  - name: Re-enable monitoring for selected hosts
    ansible.builtin.debug:
      msg: "We need to start monitoring for these host in Dynatrace: {{ inventory_hostname }} is {{ ansible_default_ipv4.address }}"
