---
- name: Check for Windows Updates
  gather_facts: no
  hosts: all

  tasks:
    - name: Check for available updates
      ansible.windows.win_updates:
        category_names: '*'  # Check all categories
        state: searched
        log_path: C:\ansible_wu.txt
      register: update_results


    - name: Print update results
      debug:
        var: update_results

    - name: Report results
      debug:
        msg: |
          {% for k in update_results.updates %}
          {{ update_results.updates[k].title }}
          {% endfor %}
