---
- name: windows server patching
  gather_facts: no
  hosts: all
  tasks:

    - name: Check for missing updates
      win_updates:
        state: searched
        log_path: C:\ansible_wu.txt
      register: update_results

          
    - name: Report results
      debug:
        msg: |
          {% for k in update_results.updates %}
          {{ update_results.updates[k].title }}
          {% endfor %}