---
# tasks file for aws_vpc

  - name: create a VPC in AWS
    amazon.aws.ec2_vpc_net:
      name: ansible_demo_dev
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ region }}"
      tags:
        name: "ansible_demo_dev_vpc"
        project: "Ansible_Demo"
    register: vpc  

  - name: create an internet gateway for the VPC
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{vpc.vpc.id}}"
    region: "{{ region }}"
    state: present
    tags:
      name: "ansible_demo_dev_igw"
      project: "Ansible_Demo"
  register: internet_gateway


  - name: create a subnet in the VPC
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{vpc.vpc.id}}"
    region: "{{ region }}"
    az: "{{ zone }}"
    state: present
    cidr: "{{ subnet_cidr_block }}"
    tags:
      name: ansible_demo_dev_subnet
  register: subnet_ids

  - name: create a route table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{vpc.vpc.id}}"
    region: "{{ region }}"
    state: present
    tags:
      Name: ansible_demo_dev_route_table
    subnets: [ "{{ subnet_ids.subnet.id }}" ]
    # create routes
    routes:
      - dest: "{{ destination_cidr_block }}"
        gateway_id: "{{ internet_gateway.gateway_id }}"
  register: public_route_table

  - name: create a security group
  ec2_group:
    name: AnsibleSecurity
    description: "Ansible Security Group"
    region: "{{region}}"
    vpc_id: "{{vpc.vpc.id}}"
    tags:
      Name: ansible_demo_dev_security_group
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "{{ security_cidr_block }}"
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ security_cidr_block }}"
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: "{{ security_cidr_block }}"
      - proto: tcp
        from_port: 3389
        to_port: 3389
        cidr_ip: "{{ security_cidr_block }}"
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: "{{ security_cidr_block }}"
      - proto: tcp
        from_port: 3389
        to_port: 3389
        cidr_ip: "{{ security_cidr_block }}"
      - proto: tcp
        from_port: 5985
        to_port: 5985
        cidr_ip: "{{ security_cidr_block }}"
      - proto: tcp
        from_port: 5986
        to_port: 5986
        cidr_ip: "{{ security_cidr_block }}"
      - proto: icmp
        from_port: -1 # icmp type, -1 = any type
        to_port:  -1 # icmp subtype, -1 = any subtype
        cidr_ip: "{{ security_cidr_block }}"
  register: my_security_group