---
- name: launching an ec2 instance
  hosts: localhost

  roles: 
  - name: "Create VPC"
    role: aws_vpc

  - name: "Create LB EC2 instance"
    role: aws_ec2
    vars:
      type: "dev_lb"
      instance_type: "t2.micro"
      server_name: 
        - "demo_lb_server"

  - name: "Create WS EC2 instance"
    role: aws_ec2
    vars:
      type: "dev_ws"
      instance_type: "t2.medium"
      server_name: 
        - "demo_ws_server_1"
        - "demo_ws_server_2"



