---
- name: Test connection to the vm with a curl
  hosts: all

  vars:
    ws_group_name: tag_dev_ws
    lb_group_name: tag_dev_lb


  tasks:

    - name: Confirm that the load balancer return a 200 code
      uri:
        url: "http://{{ ansible_host }}:80"
        validate_certs: no
        status_code: 200
      when: "'{{ lb_group_name }}' in group_names"

    - name: Confirm that the web server return a 200 code
      uri:
        url: "http://{{ ansible_host }}:8080"
        validate_certs: no
        status_code: 200
      when: "'{{ ws_group_name }}' in group_names"