## Copy this file in a -local.yml file with your values 
---
all:
  vars:
    # General variables
    GITHUB_API_BASEURL: "THE URL FOR THE API TO USE" # usually somthing like https://api.github.com/ 
    GITHUB_API_TOKEN: "[YOUR TOKEN]"
    GITHUB_HEARDER_ACCEPT: "application/vnd.github+json"
    GITHUB_API_VERSION: "2022-11-28"
    GITHUB_USERNAME: "[GITHUB REPO username]"
    GITHUB_OWNER: "[GITHUB REPO OWNER]"

    # Repository variables
    LIST_REPO_URL: "{{ GITHUB_API_BASEURL }}/users/{{GITHUB_USERNAME}}/repos?sort=full_name&per_page=100"

    # Webhook variables
    GITHUB_API_WEBHOOK_BASE_URL: "{{ GITHUB_API_BASEURL }}/repos/{{GITHUB_OWNER}}"
    WEBHOOK_URL: [THE URL FOR THEW WEBHOOK]
    WEBHOOK_SECRET: "[SECRET USE FOR THE WEBHOOK]"
