---
collections:
  - name: ansible.windows
  - name: community.windows
  - name: community.general
  - name: ansible.utils
  - name: ansible.posix
  - name: chocolatey.chocolatey
  - name: microsoft.ad

