---
# defaults file for jboss-eap-config

eap_install_workdir: '/opt'
eap_version: '7.4.0'
install_name: jboss-eap
eap_user: "{{ install_name }}"
eap_config_base: standalone-ha.xml
eap_home: "{{ eap_install_workdir }}/{{ install_name }}-{{ (eap_version.split('.'))[0:2] | join('.') }}"

instance_http_ports:
  - 8080
  - 8180
  - 8280
app:
  name: 'info-1.1.war'
  url: 'https://drive.google.com/uc?export=download&id=1w9ss5okctnjUvRAxhPEPyC7DmbUwmbhb'