---
# tasks file for haproxy-config
- name: Configure HA Load Balancer with haproxy

  block: 
      # epel = Extra Packages for Enterprise Linux
    - name: Ensure the epel repo is present
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm 
        disable_gpg_check: yes
        state: present

    - name: install haproxy
      ansible.builtin.package:
        name: haproxy
        state: present

    - name: copy haproxy conf
      ansible.builtin.template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: start and enable haproxy
      ansible.builtin.service:
        name: haproxy
        state: started
        enabled: true
  when: lb_group_name in group_names