---
- name: Create a webhook on a repository
  hosts: localhost

  tasks:
    - name: Create a webhook 
      ansible.builtin.uri:
        url: "{{ GITHUB_API_WEBHOOK_BASE_URL }}/product-service/hooks"
        method: POST
        headers:
          Accept: "{{ GITHUB_HEARDER_ACCEPT }}"
          Authorization: "Bearer {{ GITHUB_API_TOKEN }}"
          X-GitHub-Api-Version: "{{ GITHUB_API_VERSION }}"
        body_format: "json"
        body: 
          name: "web"
          active: true
          events: 
            - push
            - pull_request
          config:
            url: "{{WEBHOOK_URL}}"
            content_type: "json"
            secret: "{{WEBHOOK_SECRET}}"
            insecure_ssl: "1"
        status_code: 201
      register: repowebhook

    - name: Print the webhook info
      ansible.builtin.debug:
        var:  repowebhook.json.id