---
- name: List User repositories
  hosts: localhost

  tasks:
    - name: List available Repository for a user
      ansible.builtin.uri:
        url: "{{ LIST_REPO_URL }}"
        method: GET
        headers:
          Accept: "{{ GITHUB_HEARDER_ACCEPT }}"
          Authorization: "Bearer {{ GITHUB_API_TOKEN }}"
          X-GitHub-Api-Version: "{{ GITHUB_API_VERSION }}"
      register: list_of_repository

    - name: Print the repositories list
      ansible.builtin.debug:
        var:  item
      loop: "{{ list_of_repository | community.general.json_query('json[*].html_url') }}"