---
- name: Update secret on webhook on a repository
  hosts: localhost

  tasks:
    - name: List All Webhooks on repository
      ansible.builtin.uri:
        url: "{{ GITHUB_API_WEBHOOK_BASE_URL }}/{{REPO}}/hooks"
        method: GET
        headers:
          Accept: "{{ GITHUB_HEARDER_ACCEPT }}"
          Authorization: "Bearer {{ GITHUB_API_TOKEN }}"
          X-GitHub-Api-Version: "{{ GITHUB_API_VERSION }}"
      register: webhooks_list

    - name: Upate webhook config
      ansible.builtin.uri:
        url: "{{ GITHUB_API_WEBHOOK_BASE_URL }}/{{REPO}}/hooks/{{item}}"
        method: PATCH
        headers:
          Accept: "{{ GITHUB_HEARDER_ACCEPT }}"
          Authorization: "Bearer {{ GITHUB_API_TOKEN }}"
          X-GitHub-Api-Version: "{{ GITHUB_API_VERSION }}"
        body_format: "json"
        body: 
          config:
            url: "{{WEBHOOK_URL}}/updatedwebook"
            content_type: "json"
            secret: "{{WEBHOOK_SECRET}}"
            insecure_ssl: "0"
        status_code: 200
      loop: "{{ webhooks_list | community.general.json_query('json[*].id') }}"