---  
  - name: Create {{ tag_environment }} EC2 instance name {{ item }}
    amazon.aws.ec2_instance:
      access_key: "{{ AWS_ACCESS_KEY_ID }}"
      secret_key: "{{ AWS_SECRET_KEY }}"
      instance_type: "{{ instance_type | default('t2.medium') }}"
      region: "{{ region }}"
      image_id: "{{ image_id }}"
      security_group: "{{ securityGroup.group_name }}"
      key_name: "{{ key_name }}"
      vpc_subnet_id: "{{subnet_ids.subnet.id}}"
      network_interfaces:
        - assign_public_ip: true
      tags:
        Name: "{{ item }}"
        Type: "windowServer"
        Env: "{{ tag_environment }}"
        Project: "{{ project_name }}"
        Provider: "AWS"
      volumes:
        - device_name: /dev/sda1
          ebs:
            volume_size: 30
            volume_type: gp2
            delete_on_termination: true
      state: started
      wait: true
      user_data: "{{ lookup('template', 'userdata.txt.j2') }}"
    register: ec2_instance

  #####################################################
  # This section can be use when using ansible local. #
  #####################################################

  # - name: Get admin password
  #   community.aws.ec2_win_password:
  #     access_key: "{{ AWS_ACCESS_KEY_ID }}"
  #     secret_key: "{{ AWS_SECRET_KEY }}"
  #     instance_id: "{{ ec2_instance.instances[0].instance_id }}"
  #     region: "{{ region }}"
  #     key_file: "~/Downloads/window_farm_demo.pem"
  #     wait: true
  #   register: password

  # - name: show password {{ item }}
  #   debug:
  #     msg: "{{ password.win_password }}"     